GET http://localhost:8080/api/user

###
GET http://localhost:8080/api/user/da06cf93-7ab6-4c2f-8968-e2bff81fb125

###
POST http://localhost:8080/api/user
Accept: application/json
Content-Type: application/json


{
  "email" : "testforpassvodafone@gmail.com",
  "firstname" : "Alex",
  "lastname" : "Stavrakas"
}
