GET http://localhost:8080/api/user

###
GET http://localhost:8080/api/user/245fbfc7-6930-4ca4-96f6-2b2c8079a9f4

###
POST http://localhost:8080/api/user
Accept: application/json
Content-Type: application/json


{
  "email" : "testforpassvodafone@gmail.com",
  "firstname" : "Alex",
  "lastname" : "Stavrakas"
}
